#!/usr/bin/env python3

import os
import sys
import platform

appDir = os.path.realpath(__file__)
appDir = os.path.dirname(appDir)
appDir = os.path.dirname(appDir)
dataDir= os.path.join(appDir, 'share', 'dlna-downloader')

sys.path.insert(0, dataDir)

sys.path.insert(0, os.path.join(appDir, 'usr', 'lib', 'python3', 'dist-packages'))
sys.path.insert(0, os.path.join(appDir, 'usr', 'lib', platform.machine()+'-linux-gnu'))

from dlna_downloader import App

app = App()
app.MainLoop()
